// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownloadTasks(arg1) {
  return window['go']['main']['App']['AddDownloadTasks'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ClearCompletedTasks() {
  return window['go']['main']['App']['ClearCompletedTasks']();
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function GenerateQRCode() {
  return window['go']['main']['App']['GenerateQRCode']();
}

export function GetAvailableQualities(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAvailableQualities'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetUserInfo() {
  return window['go']['main']['App']['GetUserInfo']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenNativeBrowserLogin() {
  return window['go']['main']['App']['OpenNativeBrowserLogin']();
}

export function ParseURL(arg1) {
  return window['go']['main']['App']['ParseURL'](arg1);
}

export function PauseAllTasks() {
  return window['go']['main']['App']['PauseAllTasks']();
}

export function PauseTask(arg1) {
  return window['go']['main']['App']['PauseTask'](arg1);
}

export function PollQRCode(arg1) {
  return window['go']['main']['App']['PollQRCode'](arg1);
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function ResumeAllTasks() {
  return window['go']['main']['App']['ResumeAllTasks']();
}

export function ResumeTask(arg1) {
  return window['go']['main']['App']['ResumeTask'](arg1);
}

export function SaveRawCookie(arg1) {
  return window['go']['main']['App']['SaveRawCookie'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
